/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bdc2ff",
        "on-secondary-fixed-variant": "#354a53",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        "inverse-on-surface": "#f0f1f2",
        "surface-dim": "#d9dadb",
        "tertiary-fixed-dim": "#ffb59d",
        "surface-bright": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "primary-container": "#1a237e",
        "on-secondary-fixed": "#071e27",
        "on-background": "#191c1d",
        "on-surface-variant": "#454652",
        "on-primary-fixed": "#000767",
        "surface-variant": "#e1e3e4",
        "outline": "#767683",
        "on-tertiary-fixed": "#390c00",
        "tertiary-fixed": "#ffdbd0",
        "on-primary": "#ffffff",
        "primary": "#000666",
        "secondary-container": "#cfe6f2",
        "on-secondary-container": "#526772",
        "inverse-primary": "#bdc2ff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e0e0ff",
        "tertiary-container": "#5c1800",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#e17c5a",
        "background": "#f8f9fa",
        "surface-container": "#edeeef",
        "surface": "#f8f9fa",
        "surface-tint": "#4c56af",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed": "#cfe6f2",
        "error-container": "#ffdad6",
        "tertiary": "#380b00",
        "secondary-fixed-dim": "#b4cad6",
        "secondary": "#4c616c",
        "outline-variant": "#c6c5d4",
        "error": "#ba1a1a",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#7b2e12",
        "inverse-surface": "#2e3132",
        "on-primary-container": "#8690ee",
        "on-primary-fixed-variant": "#343d96",
        "on-error": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
